title: "Your Name – Market Insights"
baseurl: ""
url: "https://axmed0.github.io/Market-research-website/"
  
# navigation items used by your layout
nav:
  - title: "Home"
    url: /
  - title: "Market Knowledge"
    url: /market-knowledge/
  - title: "Equity Research"
    url: /equity-research/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/
