backend:
  name: git-gateway
branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Market Insights", "Equity Research", "Trade Ideas"]
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }