backend:
  name: github
  branch: main
  repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
  # For Netlify Identity + Git Gateway, swap backend to:
  # name: git-gateway

media_folder: "static/uploads"      # unused (image-free), kept for CMS compatibility
public_folder: "/static/uploads"

site_url: "https://YOUR_DOMAIN"     # update after deploy
logo_url: ""                         # image-free brand

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Market Insights", "Equity Research", "Trade Ideas"]
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }