name: Build content.json

on:
  push:
    branches: [ main ]
    paths:
      - "content/**"
      - ".github/workflows/build-content.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: |
          npm init -y >/dev/null 2>&1
          npm install gray-matter@4 >/dev/null 2>&1
          node - <<'JS'
          const fs = require('fs').promises;
          const path = require('path');
          const matter = require('gray-matter');
          async function scan(dir){const a=[];async function w(p){let e=[];try{e=await fs.readdir(p,{withFileTypes:true})}catch{return}for(const d of e){const f=path.join(p,d.name);if(d.isDirectory())await w(f);else if(/\\.md$/i.test(d.name))a.push(f)}}await w(dir);return a}
          const toSlug=s=>(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
          (async()=>{const files=await scan('content/posts');const posts=[];for(const f of files){const raw=await fs.readFile(f,'utf8');const fm=matter(raw);const d=fm.data||{};posts.push({title:d.title||'Untitled',date:d.date||new Date().toISOString(),category:d.category||'Market Insights',summary:d.summary||'',slug:d.slug||toSlug(d.title||path.basename(f,'.md')),body:(fm.content||'').trim()});}
          posts.sort((a,b)=>new Date(b.date)-new Date(a.date));
          await fs.writeFile('content.json',JSON.stringify({generatedAt:new Date().toISOString(),posts},null,2));})();
          JS
      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add content.json
            git commit -m "Build content.json"
            git push
          else
            echo "No changes to commit."
          fi
